[package]
name = "pallet-root-of-trust-rpc"
version = "2.0.1"
authors = ["Eliott Teissonniere <git.eliott@teissonniere.org>"]
edition = "2018"

[dependencies]
jsonrpc-core = "17.0.0"
jsonrpc-core-client = "17.0.0"
jsonrpc-derive = "17.0.0"
pallet-root-of-trust-runtime-api = { version = "2.0.0", path = "./runtime-api" }
parity-scale-codec = { version = "2.0.1", default_features = false }
sp-api = { version = "3.0.0", default_features = false }
sp-blockchain = { version = "3.0.0", default_features = false }
sp-runtime = { version = "3.0.0", default_features = false }
